spring.application.name=app

# Baza de date
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/car_rental}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:car_rental_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
#spring.sql.init.mode=always
# spring.jpa.defer-datasource-initialization=true

app.upload-dir=/uploads

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

